const { COMMAND_REGISTRY } = require("../utils/helpGenerator")

const PREFIX_NOTE = "Prefix form supports the server's configured prefix; examples use the default `c!`."
const ADVANCED_NOTE = "Requires Advanced Moderation to be enabled in the server settings."

const MODERATION_COMMANDS = [
    {
        name: "!warn",
        usage: "c!warn @user <reason>",
        description: `Warn a member and create a moderation case. ${PREFIX_NOTE}`,
        examples: ["c!warn @user Repeated spam", "/warn user:@user reason:Repeated spam"],
        cooldown: "none",
        permissions: ["Moderator role or moderation permission"],
        aliases: [],
    },
    {
        name: "!timeout",
        usage: "c!timeout @user [10m|2h|1d] [reason]",
        description: `Timeout a member using the prefix command. ${PREFIX_NOTE}`,
        examples: ["c!timeout @user 30m Spamming", "/timeout user:@user duration:30"],
        cooldown: "none",
        permissions: ["Moderator role or Moderate Members"],
        aliases: [],
    },
    {
        name: "!kick",
        usage: "c!kick @user [reason]",
        description: `Kick a member using the prefix command. ${PREFIX_NOTE}`,
        examples: ["c!kick @user Repeated violations", "/kick user:@user reason:Repeated violations"],
        cooldown: "none",
        permissions: ["Moderator role or Kick Members"],
        aliases: [],
    },
    {
        name: "!ban",
        usage: "c!ban @user [reason]",
        description: `Ban a user using the prefix command. ${PREFIX_NOTE}`,
        examples: ["c!ban @user Raid account", "/ban user:@user reason:Raid account"],
        cooldown: "none",
        permissions: ["Moderator role or Ban Members"],
        aliases: [],
    },
    {
        name: "!purge",
        usage: "c!purge <1-100>",
        description: `Delete recent messages in the current channel. Works in ticket and restricted channels for authorized moderators. ${PREFIX_NOTE}`,
        examples: ["c!purge 10", "/purge amount:10"],
        cooldown: "none",
        permissions: ["Manage Messages or configured moderator role"],
        botPermissions: ["Manage Messages", "Read Message History"],
        aliases: [],
    },
    {
        name: "/warn",
        usage: "/warn user:@user reason:<reason>",
        description: "Warn a member and create a moderation case.",
        examples: ["/warn user:@user reason:Breaking rules"],
        cooldown: "none",
        permissions: ["Moderator role or moderation permission"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/warnings",
        usage: "/warnings user:@user",
        description: "View a member's active warnings.",
        examples: ["/warnings user:@user"],
        cooldown: "none",
        permissions: ["Moderator role or moderation permission"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/clearwarns",
        usage: "/clearwarns user:@user [reason]",
        description: "Clear a member's active warnings.",
        examples: ["/clearwarns user:@user reason:Appeal accepted"],
        cooldown: "none",
        permissions: ["Moderator role or moderation permission"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/timeout",
        usage: "/timeout user:@user [duration] [reason]",
        description: "Timeout a member for up to 28 days.",
        examples: ["/timeout user:@user duration:30 reason:Spamming"],
        cooldown: "none",
        permissions: ["Moderator role or Moderate Members"],
        aliases: ["/mute"],
        slashOnly: true,
    },
    {
        name: "/untimeout",
        usage: "/untimeout user:@user [reason]",
        description: "Remove a member's timeout.",
        examples: ["/untimeout user:@user reason:Appeal accepted"],
        cooldown: "none",
        permissions: ["Moderator role or Moderate Members"],
        aliases: ["/unmute"],
        slashOnly: true,
    },
    {
        name: "/kick",
        usage: "/kick user:@user reason:<reason>",
        description: "Kick a member and create a moderation case.",
        examples: ["/kick user:@user reason:Repeated violations"],
        cooldown: "none",
        permissions: ["Moderator role or Kick Members"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/ban",
        usage: "/ban user:@user reason:<reason> [delete_days]",
        description: "Ban a user and optionally delete recent message history.",
        examples: ["/ban user:@user reason:Raid account delete_days:1"],
        cooldown: "none",
        permissions: ["Moderator role or Ban Members"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/unban",
        usage: "/unban user_id:<Discord ID> [reason]",
        description: "Unban a user using their Discord ID.",
        examples: ["/unban user_id:123456789012345678"],
        cooldown: "none",
        permissions: ["Moderator role or Ban Members"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/case",
        usage: "/case view|reason|revoke|delete",
        description: "View or manage an individual moderation case.",
        examples: ["/case view number:12", "/case reason number:12 reason:Updated evidence"],
        cooldown: "none",
        permissions: ["Moderator role or moderation permission"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/cases",
        usage: "/cases [user] [action] [limit]",
        description: "List and filter recent moderation cases.",
        examples: ["/cases user:@user limit:10"],
        cooldown: "none",
        permissions: ["Moderator role or moderation permission"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/purge",
        usage: "/purge amount:<1-100> [user] [bots] [contains]",
        description: `Delete a filtered batch of recent messages. ${ADVANCED_NOTE}`,
        examples: ["/purge amount:10", "/purge amount:25 user:@user"],
        cooldown: "none",
        permissions: ["Manage Messages"],
        botPermissions: ["Manage Messages", "Read Message History"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/lock",
        usage: "/lock [channel] [reason]",
        description: `Lock a text channel while preserving its previous overwrites. ${ADVANCED_NOTE}`,
        examples: ["/lock channel:#general reason:Raid response"],
        cooldown: "none",
        permissions: ["Manage Channels"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/unlock",
        usage: "/unlock [channel] [reason]",
        description: `Restore a channel from CURSED's saved lock state. ${ADVANCED_NOTE}`,
        examples: ["/unlock channel:#general"],
        cooldown: "none",
        permissions: ["Manage Channels"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/slowmode",
        usage: "/slowmode seconds:<0-21600> [channel] [reason]",
        description: `Set or disable channel slowmode. ${ADVANCED_NOTE}`,
        examples: ["/slowmode seconds:10 channel:#general"],
        cooldown: "none",
        permissions: ["Manage Channels"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/nickname",
        usage: "/nickname user:@user [nickname] [reason]",
        description: `Set or clear a member's server nickname. ${ADVANCED_NOTE}`,
        examples: ["/nickname user:@user nickname:New Name"],
        cooldown: "none",
        permissions: ["Manage Nicknames"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/tempban",
        usage: "/tempban user:@user duration:<30m|2h|7d> [reason]",
        description: `Temporarily ban a user with restart-safe expiry. ${ADVANCED_NOTE}`,
        examples: ["/tempban user:@user duration:7d reason:Raid participation"],
        cooldown: "none",
        permissions: ["Ban Members"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/softban",
        usage: "/softban user:@user [delete_days] [reason]",
        description: `Ban and immediately unban a user to remove recent messages. ${ADVANCED_NOTE}`,
        examples: ["/softban user:@user delete_days:1"],
        cooldown: "none",
        permissions: ["Ban Members"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/note",
        usage: "/note user:@user text:<private note> [evidence]",
        description: `Add a private moderator note to a user's case history. ${ADVANCED_NOTE}`,
        examples: ["/note user:@user text:Watch for repeat advertising"],
        cooldown: "none",
        permissions: ["Moderate Members"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/history",
        usage: "/history user:@user [limit]",
        description: `View a user's recent moderation history. ${ADVANCED_NOTE}`,
        examples: ["/history user:@user limit:10"],
        cooldown: "none",
        permissions: ["Moderate Members"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/welcome",
        usage: "/welcome setup|view|preview|test|disable",
        description: "Configure, preview, test, or disable welcome messages and cards.",
        examples: ["/welcome setup channel:#welcome", "/welcome preview"],
        cooldown: "none",
        permissions: ["Manage Server"],
        aliases: [],
        slashOnly: true,
    },
    {
        name: "/autorole",
        usage: "/autorole set|disable|view",
        description: "Configure the role assigned to new members.",
        examples: ["/autorole set role:@Member", "/autorole view"],
        cooldown: "none",
        permissions: ["Manage Roles"],
        aliases: [],
        slashOnly: true,
    },
]

function applyHelpCatalog() {
    if (!COMMAND_REGISTRY.moderation) return false
    COMMAND_REGISTRY.moderation.description = "Prefix and slash moderation commands currently deployed by CURSED. Commands that require Advanced Moderation are marked in their descriptions."
    COMMAND_REGISTRY.moderation.commands = MODERATION_COMMANDS.map(command => ({ ...command }))
    return true
}

applyHelpCatalog()

module.exports = {
    MODERATION_COMMANDS,
    applyHelpCatalog,
}
