const { AttachmentBuilder } = require("discord.js")

function escapeHtml(value) {
    return String(value ?? "")
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;")
}

async function fetchAllMessages(channel, limit = 1000) {
    const messages = []
    let before
    while (messages.length < limit) {
        const batch = await channel.messages.fetch({ limit: Math.min(100, limit - messages.length), before })
        if (!batch.size) break
        messages.push(...batch.values())
        before = batch.last().id
        if (batch.size < 100) break
    }
    return messages.sort((a, b) => a.createdTimestamp - b.createdTimestamp)
}

function renderMessage(message) {
    const author = escapeHtml(message.author?.tag || message.author?.username || "Unknown")
    const avatar = escapeHtml(message.author?.displayAvatarURL?.({ extension: "png", size: 64 }) || "")
    const time = new Date(message.createdTimestamp).toISOString()
    const content = escapeHtml(message.cleanContent || message.content || "").replace(/\n/g, "<br>")
    const attachments = [...message.attachments.values()].map(item => {
        const url = escapeHtml(item.url)
        return `<a class="attachment" href="${url}" target="_blank" rel="noreferrer">📎 ${escapeHtml(item.name || "attachment")}</a>`
    }).join("")
    const embeds = message.embeds.length ? `<div class="embed-note">${message.embeds.length} embed(s)</div>` : ""
    return `<article class="message"><img src="${avatar}" alt=""><div><header><strong>${author}</strong><time>${time}</time></header><div class="body">${content || "<em>No text content</em>"}</div>${attachments}${embeds}</div></article>`
}

async function createTranscriptAttachment(channel, ticket) {
    const messages = await fetchAllMessages(channel)
    const rows = messages.map(renderMessage).join("\n")
    const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>CURSED Ticket #${ticket.ticketNumber}</title><style>body{margin:0;background:#09070f;color:#eee;font:15px system-ui}.wrap{max-width:900px;margin:auto;padding:32px}.hero{padding:24px;border:1px solid #6d28d9;border-radius:18px;background:linear-gradient(135deg,#171124,#0d0915);box-shadow:0 0 50px #7c3aed22}.hero h1{margin:0;color:#c4b5fd}.meta{color:#a8a0b5;margin-top:8px}.message{display:grid;grid-template-columns:44px 1fr;gap:12px;padding:16px 0;border-bottom:1px solid #ffffff12}.message img{width:40px;height:40px;border-radius:50%}.message header{display:flex;gap:10px;align-items:center}.message time{font-size:12px;color:#837b91}.body{margin-top:5px;line-height:1.5;word-break:break-word}.attachment{display:block;color:#a78bfa;margin-top:7px}.embed-note{border-left:3px solid #8b5cf6;padding:8px;margin-top:8px;color:#aaa}footer{margin-top:28px;color:#756d82;text-align:center}</style></head><body><main class="wrap"><section class="hero"><h1>CURSED Ticket #${ticket.ticketNumber}</h1><div class="meta">${escapeHtml(ticket.categoryLabel)} • ${escapeHtml(ticket.creatorTag)} • ${escapeHtml(ticket.status)}</div></section><section>${rows || "<p>No messages were found.</p>"}</section><footer>Generated by CURSED Support • ${new Date().toISOString()}</footer></main></body></html>`
    return new AttachmentBuilder(Buffer.from(html, "utf8"), { name: `cursed-ticket-${ticket.ticketNumber}.html` })
}

module.exports = { createTranscriptAttachment, fetchAllMessages }
